name = "lake-personal-menu"
name_pretty = "Lake's Personal Menu"
action = "%VALUE%"
fixed_order = true
history = false

[[entries]]
text = "Lakeside Rice Loader"
value = "walker --provider menus:lakeside-rice-loader --hideqa -N"

[[entries]]
text = "Static Wallpapers"
value = "walker --provider menus:st-wp --hideqa -N"

#[[entries]]
#text = "Live Wallpapers"
#subtext = "kinda heavy though"
#value = "walker --provider menus:live-wp --hideqa -N"

[[entries]]
text = "Hyprpicker"
value = "hyprpicker -a"