# bkg color taken with matcha gtk theme midnight dark azul variant enabled

windowrule = match:class thunar, darkwindow:shade chromakey bkg=[0.0941176470 0.1019607843 0.1215686274] similarity=$sim amount=$amt targetOpacity=$app_opct
windowrule = match:class org.xfce.mousepad, darkwindow:shade chromakey bkg=[0.0941176470 0.1019607843 0.1215686274] similarity=$sim amount=$sim targetOpacity=$app_opct

windowrule = match:class engrampa, darkwindow:shade chromakey bkg=[0.0745098039 0.0823529411 0.1019607843] similarity=$sim amount=$amt targetOpacity=$app_opct
windowrule = match:class nwg-look, darkwindow:shade chromakey bkg=[0.0745098039 0.0823529411 0.1019607843] similarity=$sim amount=$amt targetOpacity=$app_opct
